id: tsp
type: algorithm
topic: graphs
name:
  es: "Travelling salesman problem"
  en: "Travelling salesman problem"
level: advanced
difficulty: 5.0
techniques: []
tags: []
prerequisites: []
current_version: v1
wip: true
