id: sieve
type: algorithm
topic: arithmetics
name:
  es: "Sieve of Eratosthenes"
  en: "Sieve of Eratosthenes"
level: beginner
difficulty: 2.0
techniques: []
tags: []
prerequisites: []
current_version: v1
wip: true
