id: priority-queue
type: structure
topic: data-structures
name:
  es: "Priority queue (heap)"
  en: "Priority queue (heap)"
level: beginner
difficulty: 2.0
techniques: []
tags: []
prerequisites: []
current_version: v1
wip: true
