id: newton-binomial
type: technique
topic: combinatorics
name:
  es: "Newtons binomial"
  en: "Newtons binomial"
level: intermediate
difficulty: 3.5
techniques: []
tags: []
prerequisites: []
current_version: v1
wip: true
