#!/usr/bin/env python3
"""Generate ``docs/assets/js/taxonomy.js`` from the taxonomy in ``common.py``.

The taxonomy (difficulty levels, content types, topics, language labels) used to
be declared twice: once in Python (``tools/common.py``, used by the generators)
and again by hand in the front-end (``catalog.js`` / ``cheatsheet-builder.js``).
This script removes that duplication: ``common.py`` is the single source, and
this generator writes a tiny ``taxonomy.js`` that exposes the same values to the
browser as ``window.Taxonomy``. ``catalog.js`` reads from it (and must be loaded
after it — see ``mkdocs.yml`` ``extra_javascript``).

Add a level/type/topic in ``common.py`` and re-run ``python tools/gen.py
generate`` — it appears everywhere, front-end included, with no hand edits.

Every write goes through ``common.write_if_changed`` so ``--check`` is an
accurate dry-run, matching the other generators.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import common  # noqa: E402

OUTPUT_PATH = common.DOCS_DIR / "assets" / "js" / "taxonomy.js"


def _payload() -> dict:
    return {
        "LEVELS": list(common.LEVELS),
        "LEVEL_LABELS": dict(common.LEVEL_LABELS),
        "TYPES": list(common.TYPES),
        "TYPE_LABELS": dict(common.TYPE_LABELS),
        "TOPICS": {k: dict(v) for k, v in common.TOPICS.items()},
        "TOPIC_IDS": list(common.TOPIC_IDS),
        # ext -> display name (e.g. {"cpp": "C++", "py": "Python"})
        "LANG_LABELS": {ext: meta["name"] for ext, meta in common.LANGUAGES.items()},
    }


def render() -> str:
    data = json.dumps(_payload(), ensure_ascii=False, indent=2, sort_keys=False)
    return (
        "/* AUTO-GENERATED by tools/gentaxonomy.py from tools/common.py — do not edit.\n"
        " * The taxonomy (levels, types, topics, language labels) lives in Python\n"
        " * (tools/common.py); this file mirrors it to the browser as window.Taxonomy.\n"
        " * Regenerate: python tools/gen.py generate */\n"
        f"window.Taxonomy = {data};\n"
    )


def generate(check: bool = False) -> list[common.Change]:
    return [common.write_if_changed(OUTPUT_PATH, render(), check)]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="gentaxonomy.py",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=__doc__,
    )
    parser.add_argument(
        "--check", action="store_true",
        help="Dry-run: do not write; exit non-zero if taxonomy.js is stale (CI mode).",
    )
    args = parser.parse_args(argv)
    changes = generate(check=args.check)
    pending = common.print_plan(changes, check=args.check, title="gentaxonomy: assets/js/taxonomy.js from common.py")
    if args.check and pending:
        print("\ntaxonomy.js out of date. Run: python tools/gentaxonomy.py")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
