#!/usr/bin/env python3
"""Generate per-algorithm test fixtures from the ``examples`` block in meta.yaml.

Each algorithm's ``meta.yaml`` carries an ``examples:`` list where every item has
an ``input`` (fed to the test driver on stdin) and an ``expected_output`` (the
stdout the driver must produce), plus an optional ``title``. Those examples are
*dual-purpose*: they are rendered in the docs **and** executed as tests
(see ``.devs/v2-design.md`` §3 and §7).

This script materialises those examples as on-disk fixture files so the test
runner (``tools/runtests.py``) can pipe them through each code variant:

    <algo>/test/cases/01.in   <-  example[0].input
    <algo>/test/cases/01.out  <-  example[0].expected_output
    <algo>/test/cases/02.in   <-  example[1].input
    ...

Numbering is 1-based, zero-padded to two digits, in the order the examples are
listed in ``meta.yaml``. Content is preserved exactly, normalised to end with a
single trailing newline. A ``README.txt`` is dropped alongside the cases noting
they are auto-generated (do not hand-edit).

The hand-written test drivers (``test/driver.cpp`` / ``test/driver.py``) are the
author's responsibility and are **never** created or touched here. If an
algorithm has generated cases but no driver, a warning is emitted (verbose mode)
because the cases cannot be run without one.

Every write goes through ``common.write_if_changed`` so ``--check`` is an
accurate dry-run (and exits non-zero when anything is pending), matching the
other generators.

Examples
--------
    python tools/gentests.py                 # generate fixtures for every algorithm
    python tools/gentests.py --check          # CI dry-run: fail if anything is stale
    python tools/gentests.py --algo fenwick-tree -v
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import common  # noqa: E402


# Files auto-generated here are the pair of every example plus a README.
DRIVER_NAMES = ("driver.cpp", "driver.py")

README_TEXT = """\
AUTO-GENERATED test fixtures — do not edit.

These *.in / *.out files are generated by tools/gentests.py from the
`examples:` block of the algorithm's meta.yaml. Each example becomes one
pair, numbered in listing order:

    NN.in   <- example input        (piped to the driver on stdin)
    NN.out  <- example expected_output (the stdout the driver must print)

To change a case, edit `examples:` in ../../meta.yaml and re-run:

    python tools/gentests.py

The test drivers (../driver.cpp, ../driver.py) are hand-written and are NOT
generated by this script.
"""


def _normalise(text: str | None) -> str:
    """Preserve content exactly, but guarantee a single trailing newline."""
    if text is None:
        text = ""
    return text.rstrip("\n") + "\n"


def _examples(algo: common.Algorithm) -> list[dict]:
    """Return the algorithm's examples list (empty if absent/malformed)."""
    examples = algo.meta.get("examples")
    if not isinstance(examples, list):
        return []
    return [e for e in examples if isinstance(e, dict)]


def generate(check: bool = False, algo: str | None = None) -> list[common.Change]:
    """Generate test fixtures for all algorithms (or the one matching ``algo``).

    Returns every :class:`common.Change` this run makes (or would make in
    ``check`` mode), including ``unchanged`` ones, so callers can report a full
    plan and decide the exit status.
    """
    changes: list[common.Change] = []

    for a in common.iter_algorithms(only=algo):
        if a.is_article:
            continue  # articles are not tested
        examples = _examples(a)
        if not examples:
            # Nothing to generate; skipped silently here (reported in verbose main()).
            continue

        cases_dir = a.test_dir / "cases"
        for i, example in enumerate(examples, start=1):
            stem = f"{i:02d}"
            in_change = common.write_if_changed(
                cases_dir / f"{stem}.in",
                _normalise(example.get("input")),
                check,
            )
            out_change = common.write_if_changed(
                cases_dir / f"{stem}.out",
                _normalise(example.get("expected_output")),
                check,
            )
            changes.append(in_change)
            changes.append(out_change)

        changes.append(
            common.write_if_changed(cases_dir / "README.txt", README_TEXT, check)
        )

    return changes


def _drivers_present(algo: common.Algorithm) -> bool:
    return any((algo.test_dir / name).exists() for name in DRIVER_NAMES)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="gentests.py",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=(
            "Generate test fixture files (cases/NN.in / NN.out) for every "
            "algorithm from the `examples` block of its meta.yaml.\n\n"
            "The examples are the single source of truth shared by the docs and "
            "the tests: each example's `input` becomes an NN.in file and its "
            "`expected_output` becomes the matching NN.out, numbered 1-based in "
            "listing order under <algo>/test/cases/. Content is copied verbatim "
            "and normalised to a single trailing newline.\n\n"
            "The hand-written drivers (test/driver.cpp, test/driver.py) are never "
            "created or overwritten. Use --check in CI to fail when fixtures are "
            "out of date with meta.yaml."
        ),
        epilog=(
            "Examples:\n"
            "  python tools/gentests.py                # regenerate all fixtures\n"
            "  python tools/gentests.py --check        # dry-run; non-zero if stale\n"
            "  python tools/gentests.py --algo loops -v\n"
        ),
    )
    parser.add_argument(
        "--algo",
        metavar="ID",
        default=None,
        help="Only process the algorithm with this meta.yaml `id` "
        "(e.g. fenwick-tree). Default: all algorithms.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Dry-run: do not write anything, only report what would change. "
        "Exit non-zero if any fixture is missing or out of date (CI mode).",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Print extra diagnostics: algorithms skipped for having no "
        "examples, and warnings when generated cases lack a test driver.",
    )
    args = parser.parse_args(argv)

    changes = generate(check=args.check, algo=args.algo)

    if args.verbose:
        for a in common.iter_algorithms(only=args.algo):
            examples = _examples(a)
            if not examples:
                print(f"  skip (no examples): {a.id}")
                continue
            if not _drivers_present(a):
                rel = (a.test_dir).relative_to(common.REPO_ROOT)
                print(
                    f"  WARNING: {a.id} has {len(examples)} generated case(s) "
                    f"but no driver in {rel}/ — add driver.cpp and/or driver.py "
                    f"to run them."
                )

    pending = common.print_plan(
        changes, check=args.check, title="gentests: fixtures from meta.yaml examples"
    )

    if args.check and pending:
        print(f"\n{pending} fixture file(s) out of date. Run: python tools/gentests.py")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
